[base]
dimension = 1
output_dir = "output"

[solver]
name = "aenet"

[solver.config]
aenet_exec_file = "predict.x"
aenet_ann_potential = "N.5t-5t.ann"

[solver.param]
string_list = ["value_01"]

[algorithm]
name = "pamc"
label_list = ["z"]

[algorithm.param]
min_list = [0.5]
max_list = [2.0]
unit_list = [0.015]

[algorithm.pamc]
numsteps_per_T = 40
downTsteps_resampling = 2
Tnum = 41
Tmin = 1
Tmax = 1000
replica_per_prop = 10
Tlogspace = true
resampling_bool = true
use_so_for_walker_table = false
use_so_for_resampling = true
