[base]
dimension = 1
output_dir = "output"

[solver]
name = "aenet"

[solver.config]
aenet_exec_file = "predict.x"
aenet_ann_potential = "N.5t-5t.ann"

[solver.param]
string_list = ["value_01"]

[algorithm]
name = "minsearch"
label_list = ["z"]

[algorithm.param]
min_list = [0.5]
max_list = [2.0]
initial_list = [1.25]

[algorithm.minimize]
initial_scale_list = [0.25]
xatol = 0.0001
fatol = 0.0001
maxiter = 100
